matrix:
- name: markdown
  pipeline:
  - pyspelling.filters.text
  default_encoding: utf-8
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  sources:
  - '**/*.md'