title: "Resume Dirk van Zon"
description: "Full-stack developer"
theme: minima
baseurl: ""

google_analytics: G-5WSH8VXPEL

minima:
  skin: auto
  social_links:
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/dirk-van-zon-1a677a293"
    - title: GitHub
      icon: github
      url: "https://github.com/dirkzon"

author:
  name: Dirk van Zon
  email: "dirk.v.zon@outlook.com"

exclude:
  - docker-compose.yml
  - .gitignore
  - README.md
  - LICENCE
