title: "My Resume"
description: "A simple online resume built with GitHub Pages and Jekyll"
theme: minima

exclude:
  - docker-compose.yml
  - .gitignore

minima:
  skin: classic
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/dirkzon"
    - title: Linkedin
      icon: linkedin
      url: "https://linkedin.com/in/dirk-van-zon-1a677a293"