title: "Dirk van Zon"
description: "Full-stack developer"
theme: minima
baseurl: ""

minima:
  skin: auto

author:
  name: Dirk van Zon
  email: "dirk.v.zon@outlook.com"

exclude:
  - docker-compose.yml
  - .gitignore
  - README.md
  - LICENCE
