name: Spellcheck
on:
  push:
    paths:
    - 'index.md'

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Spellcheck Action    
      uses: rojopolis/spellcheck-github-actions@0.47.0
